"""10-10-24

Revision ID: 45222eca504f
Revises: a253d7e844c0
Create Date: 2024-10-10 13:07:53.205184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45222eca504f'
down_revision: Union[str, None] = 'a253d7e844c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chat_messages_sender_id_fkey', 'chat_messages', type_='foreignkey')
    op.drop_constraint('chat_messages_recipient_id_fkey', 'chat_messages', type_='foreignkey')
    op.create_foreign_key(None, 'chat_messages', 'user_metadata', ['recipient_id'], ['user_metadata_id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key(None, 'chat_messages', 'user_metadata', ['sender_id'], ['user_metadata_id'], onupdate='CASCADE', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.create_foreign_key('chat_messages_recipient_id_fkey', 'chat_messages', 'user_metadata', ['recipient_id'], ['user_metadata_id'])
    op.create_foreign_key('chat_messages_sender_id_fkey', 'chat_messages', 'user_metadata', ['sender_id'], ['user_metadata_id'])
    # ### end Alembic commands ###
