"""roles + pydantic

Revision ID: 62d7efd55312
Revises: 8c5ad0df48bb
Create Date: 2024-09-12 19:33:27.334096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '62d7efd55312'
down_revision: Union[str, None] = '8c5ad0df48bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # удаление зависимых таблиц 
    op.drop_table('rolepermission')
    op.drop_table('user_permission')
    # удаление основной таблицы
    op.drop_table('permission')
    # удалеие других таблиц
    op.drop_table('user_role')
    op.drop_column('user_metadata', 'role_id')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_metadata', sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_table('user_role',
    sa.Column('user_role_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.role_id'], name='user_role_role_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name='user_role_user_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_role_id', name='user_role_pkey'),
    sa.UniqueConstraint('user_role_id', name='user_role_user_role_id_key')
    )
    op.create_table('user_permission',
    sa.Column('user_permission_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('permission_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.permission_id'], name='user_permission_permission_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name='user_permission_user_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_permission_id', name='user_permission_pkey'),
    sa.UniqueConstraint('user_permission_id', name='user_permission_user_permission_id_key')
    )
    op.create_table('rolepermission',
    sa.Column('rolepermissions_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('permission_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.permission_id'], name='rolepermission_permission_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['role.role_id'], name='rolepermission_role_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rolepermissions_id', name='rolepermission_pkey'),
    sa.UniqueConstraint('rolepermissions_id', name='rolepermission_rolepermissions_id_key')
    )
    op.create_table('permission',
    sa.Column('permission_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('permission_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('permission_details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('permission_id', name='permission_pkey'),
    sa.UniqueConstraint('permission_id', name='permission_permission_id_key'),
    sa.UniqueConstraint('permission_name', name='permission_permission_name_key')
    )
    # ### end Alembic commands ###
