"""TeperCho

Revision ID: 829658d29e7c
Revises: 10a30c4786fe
Create Date: 2024-08-16 12:36:54.650308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '829658d29e7c'
down_revision: Union[str, None] = '10a30c4786fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('image', sa.String(), nullable=True))
    op.alter_column('event', 'rewards',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    op.add_column('user_metadata', sa.Column('status', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_metadata', 'status')
    op.alter_column('event', 'rewards',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('event', 'image')
    # ### end Alembic commands ###
