"""only roles

Revision ID: 8c5ad0df48bb
Revises: 3b0871440725
Create Date: 2024-09-12 12:11:16.232848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c5ad0df48bb'
down_revision: Union[str, None] = '3b0871440725'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_volunteer', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('is_cityadm', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('is_regionadm', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('is_superadm', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_superadm')
    op.drop_column('user', 'is_regionadm')
    op.drop_column('user', 'is_cityadm')
    op.drop_column('user', 'is_volunteer')
    # ### end Alembic commands ###
