"""Newest

Revision ID: a253d7e844c0
Revises: a3d712771730
Create Date: 2024-09-20 18:24:40.122345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a253d7e844c0'
down_revision: Union[str, None] = 'a3d712771730'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_metadata', sa.Column('avatar_image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_metadata', 'avatar_image')
    # ### end Alembic commands ###
