"""roles + pydantic pt. 2

Revision ID: a3d712771730
Revises: 62d7efd55312
Create Date: 2024-09-12 19:38:06.784425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3d712771730'
down_revision: Union[str, None] = '62d7efd55312'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('role_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('role_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('role_id', name='role_pkey'),
    sa.UniqueConstraint('role_id', name='role_role_id_key'),
    sa.UniqueConstraint('role_name', name='role_role_name_key')
    )
    # ### end Alembic commands ###
